<?php

namespace App\Exports;

use App\Models\Report;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;

class ReportsExport implements FromCollection, WithHeadings, WithMapping
{
    protected $reports;

    public function __construct($reports)
    {
        $this->reports = $reports;
    }

    public function collection()
    {
        return $this->reports;
    }

    public function headings(): array
    {
        return [
            'ID',
            'Report Name',
            'Type',
            'Generated By',
            'Status',
            'File Size',
            'Created At',
            'Updated At'
        ];
    }

    public function map($report): array
    {
        return [
            $report->id,
            $report->name ?? 'Unnamed Report',
            $report->type ?? 'general',
            $report->generated_by ?? 'System',
            $report->status ?? 'unknown',
            $report->file_size ?? 'N/A',
            $report->created_at?->format('Y-m-d H:i:s') ?? '',
            $report->updated_at?->format('Y-m-d H:i:s') ?? '',
        ];
    }
}