<!DOCTYPE html>
<html>
<head>
    <title>Reports Export</title>
    <style>
        body { font-family: Arial, sans-serif; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
    </style>
</head>
<body>
    <h1>Reports Export</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Report Name</th>
                <th>Type</th>
                <th>Generated By</th>
                <th>Status</th>
                <th>File Size</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            <?php $__currentLoopData = $reports; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $report): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <tr>
                <td><?php echo e($report->id); ?></td>
                <td><?php echo e($report->name ?? 'Unnamed Report'); ?></td>
                <td><?php echo e($report->type ?? 'general'); ?></td>
                <td><?php echo e($report->generated_by ?? 'System'); ?></td>
                <td><?php echo e($report->status ?? 'unknown'); ?></td>
                <td><?php echo e($report->file_size ?? 'N/A'); ?></td>
                <td><?php echo e($report->created_at?->format('Y-m-d H:i:s') ?? ''); ?></td>
            </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </tbody>
    </table>
</body>
</html><?php /**PATH C:\Users\pprhl\cls_management\resources\views/reports/exports/pdf.blade.php ENDPATH**/ ?>