<!DOCTYPE html>
<html>
<head>
    <title>Reports Export</title>
    <style>
        body { font-family: Arial, sans-serif; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
    </style>
</head>
<body>
    <h1>Reports Export</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Report Name</th>
                <th>Type</th>
                <th>Generated By</th>
                <th>Status</th>
                <th>File Size</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reports as $report)
            <tr>
                <td>{{ $report->id }}</td>
                <td>{{ $report->name ?? 'Unnamed Report' }}</td>
                <td>{{ $report->type ?? 'general' }}</td>
                <td>{{ $report->generated_by ?? 'System' }}</td>
                <td>{{ $report->status ?? 'unknown' }}</td>
                <td>{{ $report->file_size ?? 'N/A' }}</td>
                <td>{{ $report->created_at?->format('Y-m-d H:i:s') ?? '' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>