<?php

namespace App\Http\Controllers;

use App\Models\Report;
use App\Models\Land;
use App\Models\Chief;
use App\Models\Client;
use App\Models\Allocation;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use Barryvdh\DomPDF\Facade\Pdf;

class ReportController extends Controller
{
    /**
     * Display the main reports index page.
     */
    public function index(Request $request): View
    {
        $search = $request->input('search');
        $type = $request->input('type');

        $query = Report::with('generatedBy');

        if ($search) {
            $query->where('name', 'like', "%{$search}%")
                  ->orWhere('type', 'like', "%{$search}%");
        }

        if ($type) {
            $query->where('type', $type);
        }

        $reports = $query->latest()->paginate(15);

        // Statistics for the dashboard
        $reportsThisMonth = Report::whereMonth('created_at', now()->month)
            ->whereYear('created_at', now()->year)
            ->count();

        // Count all reports as ready for export since we don't have status column
        $readyForExport = $reports->count();

        return view('reports.index', compact(
            'reports',
            'reportsThisMonth',
            'readyForExport'
        ));
    }

    /**
     * Export reports list (for the export button functionality)
     */
    public function export(Request $request)
    {
        $search = $request->input('search');
        $type = $request->input('type');
        $format = $request->input('format', 'csv');
        
        // Get filtered reports based on the request parameters
        $query = Report::query();
        
        if ($search) {
            $query->where('name', 'like', "%{$search}%")
                  ->orWhere('type', 'like', "%{$search}%");
        }
        
        if ($type) {
            $query->where('type', $type);
        }
        
        $reports = $query->get();
        
        // Generate filename with timestamp
        $filename = 'reports_export_' . now()->format('Y_m_d_His') . '.' . $format;
        
        // Handle different export formats
        switch ($format) {
            case 'pdf':
                return $this->exportPdf($reports, $filename);
                
            case 'excel':
            case 'csv':
            default:
                return $this->exportCsv($reports, $filename);
        }
    }

    /**
     * Export to PDF
     */
    private function exportPdf($reports, $filename)
    {
        try {
            $pdf = PDF::loadView('reports.exports.pdf', compact('reports'));
            return $pdf->download($filename);
        } catch (\Exception $e) {
            // Fallback to CSV if PDF generation fails
            return $this->exportCsv($reports, str_replace('.pdf', '.csv', $filename));
        }
    }

    /**
     * Export to CSV
     */
    private function exportCsv($reports, $filename)
    {
        $headers = [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => "attachment; filename=\"$filename\"",
        ];

        $callback = function() use ($reports) {
            $file = fopen('php://output', 'w');
            
            // Add BOM for UTF-8
            fwrite($file, "\xEF\xBB\xBF");
            
            // Add CSV headers - only available columns
            fputcsv($file, [
                'ID', 'Report Name', 'Type', 'Generated By', 'Created At', 'Updated At'
            ]);
            
            // Add data rows - only available columns
            foreach ($reports as $report) {
                fputcsv($file, [
                    $report->id,
                    $report->name ?? 'Unnamed Report',
                    $report->type ?? 'general',
                    $report->generated_by ?? 'System',
                    $report->created_at?->format('Y-m-d H:i:s') ?? '',
                    $report->updated_at?->format('Y-m-d H:i:s') ?? '',
                ]);
            }
            
            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }

    /**
     * Display lands report (HTML view)
     */
    public function landReport(Request $request): View
    {
        $request->validate([
            'start_date' => 'nullable|date',
            'end_date' => 'nullable|date|after_or_equal:start_date',
            'chief_id' => 'nullable|exists:chiefs,id',
            'status' => 'nullable|string'
        ]);

        $lands = Land::with(['chief', 'allocation.client'])
            ->when($request->start_date, function($query) use ($request) {
                $query->where('registration_date', '>=', $request->start_date);
            })
            ->when($request->end_date, function($query) use ($request) {
                $query->where('registration_date', '<=', $request->end_date);
            })
            ->when($request->chief_id, function($query) use ($request) {
                $query->where('chief_id', $request->chief_id);
            })
            ->when($request->status, function($query) use ($request) {
                $query->where('ownership_status', $request->status);
            })
            ->latest()
            ->get();

        $chiefs = Chief::where('is_active', true)->get();

        return view('reports.lands', compact('lands', 'chiefs'));
    }

    /**
     * Generate and download land report (PDF/Excel)
     */
    public function generateLandReport(Request $request)
    {
        $request->validate([
            'start_date' => 'nullable|date',
            'end_date' => 'nullable|date|after_or_equal:start_date',
            'chief_id' => 'nullable|exists:chiefs,id',
            'status' => 'nullable|string',
            'format' => 'required|in:pdf,excel'
        ]);

        // For now, redirect to CSV export to avoid Excel package issues
        if ($request->format === 'excel') {
            return $this->exportLandReport($request);
        }

        // PDF report
        $lands = Land::with(['chief', 'allocation.client'])
            ->when($request->start_date, function($query) use ($request) {
                $query->where('registration_date', '>=', $request->start_date);
            })
            ->when($request->end_date, function($query) use ($request) {
                $query->where('registration_date', '<=', $request->end_date);
            })
            ->when($request->chief_id, function($query) use ($request) {
                $query->where('chief_id', $request->chief_id);
            })
            ->when($request->status, function($query) use ($request) {
                $query->where('ownership_status', $request->status);
            })
            ->get();

        $pdf = PDF::loadView('reports.lands-pdf', compact('lands'));

        // Save report record
        Report::create([
            'name' => 'Lands Report - ' . date('Y-m-d'),
            'type' => 'lands',
            'date_range' => [
                'start' => $request->start_date,
                'end' => $request->end_date
            ],
            'generated_by' => auth()->id(),
            'file_path' => 'reports/lands-report-' . date('Y-m-d') . '.pdf',
            'parameters' => $request->all()
        ]);

        return $pdf->download('lands-report-' . date('Y-m-d') . '.pdf');
    }

    /**
     * Quick export land report
     */
    public function exportLandReport(Request $request)
    {
        $filters = $request->only(['start_date', 'end_date', 'chief_id', 'status']);
        
        // Create CSV export for lands
        $lands = Land::with(['chief', 'allocation.client'])
            ->when($filters['start_date'] ?? null, function($query) use ($filters) {
                $query->where('registration_date', '>=', $filters['start_date']);
            })
            ->when($filters['end_date'] ?? null, function($query) use ($filters) {
                $query->where('registration_date', '<=', $filters['end_date']);
            })
            ->when($filters['chief_id'] ?? null, function($query) use ($filters) {
                $query->where('chief_id', $filters['chief_id']);
            })
            ->when($filters['status'] ?? null, function($query) use ($filters) {
                $query->where('ownership_status', $filters['status']);
            })
            ->get();

        $filename = 'lands-report-' . date('Y-m-d') . '.csv';
        $headers = [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => "attachment; filename=\"$filename\"",
        ];

        $callback = function() use ($lands) {
            $file = fopen('php://output', 'w');
            fwrite($file, "\xEF\xBB\xBF"); // UTF-8 BOM
            
            fputcsv($file, [
                'ID', 'Plot Number', 'Location', 'Size (acres)', 'Chief', 
                'Status', 'Price', 'Registration Date'
            ]);
            
            foreach ($lands as $land) {
                fputcsv($file, [
                    $land->id,
                    $land->plot_number ?? 'N/A',
                    $land->location ?? 'N/A',
                    $land->size ?? '0',
                    $land->chief->name ?? 'No Chief',
                    $land->ownership_status ?? 'unknown',
                    $land->price ?? '0',
                    $land->registration_date?->format('Y-m-d') ?? '',
                ]);
            }
            
            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }

    /**
     * Display allocations report (HTML view)
     */
    public function allocationReport(Request $request): View
    {
        $request->validate([
            'start_date' => 'nullable|date',
            'end_date' => 'nullable|date|after_or_equal:start_date',
            'status' => 'nullable|string',
            'chief_id' => 'nullable|exists:chiefs,id'
        ]);

        $allocations = Allocation::with(['land', 'client', 'chief'])
            ->when($request->start_date, function($query) use ($request) {
                $query->where('allocation_date', '>=', $request->start_date);
            })
            ->when($request->end_date, function($query) use ($request) {
                $query->where('allocation_date', '<=', $request->end_date);
            })
            ->when($request->status, function($query) use ($request) {
                $query->where('approval_status', $request->status);
            })
            ->when($request->chief_id, function($query) use ($request) {
                $query->where('chief_id', $request->chief_id);
            })
            ->latest()
            ->get();

        $chiefs = Chief::where('is_active', true)->get();

        return view('reports.allocations', compact('allocations', 'chiefs'));
    }

    /**
     * Generate and download allocation report
     */
    public function generateAllocationReport(Request $request)
    {
        $request->validate([
            'start_date' => 'nullable|date',
            'end_date' => 'nullable|date|after_or_equal:start_date',
            'status' => 'nullable|string',
            'chief_id' => 'nullable|exists:chiefs,id',
            'format' => 'required|in:pdf,excel'
        ]);

        // For now, redirect to CSV export
        if ($request->format === 'excel') {
            return $this->exportAllocationReport($request);
        }

        // PDF implementation
        $allocations = Allocation::with(['land', 'client', 'chief'])
            ->when($request->start_date, function($query) use ($request) {
                $query->where('allocation_date', '>=', $request->start_date);
            })
            ->when($request->end_date, function($query) use ($request) {
                $query->where('allocation_date', '<=', $request->end_date);
            })
            ->when($request->status, function($query) use ($request) {
                $query->where('approval_status', $request->status);
            })
            ->when($request->chief_id, function($query) use ($request) {
                $query->where('chief_id', $request->chief_id);
            })
            ->get();

        $pdf = PDF::loadView('reports.allocations-pdf', compact('allocations'));

        // Save report record
        Report::create([
            'name' => 'Allocations Report - ' . date('Y-m-d'),
            'type' => 'allocations',
            'date_range' => [
                'start' => $request->start_date,
                'end' => $request->end_date
            ],
            'generated_by' => auth()->id(),
            'file_path' => 'reports/allocations-report-' . date('Y-m-d') . '.pdf',
            'parameters' => $request->all()
        ]);

        return $pdf->download('allocations-report-' . date('Y-m-d') . '.pdf');
    }

    /**
     * Quick export allocation report
     */
    public function exportAllocationReport(Request $request)
    {
        $filters = $request->only(['start_date', 'end_date', 'status', 'chief_id']);
        
        // Create CSV export for allocations
        $allocations = Allocation::with(['land', 'client', 'chief'])
            ->when($filters['start_date'] ?? null, function($query) use ($filters) {
                $query->where('allocation_date', '>=', $filters['start_date']);
            })
            ->when($filters['end_date'] ?? null, function($query) use ($filters) {
                $query->where('allocation_date', '<=', $filters['end_date']);
            })
            ->when($filters['status'] ?? null, function($query) use ($filters) {
                $query->where('approval_status', $filters['status']);
            })
            ->when($filters['chief_id'] ?? null, function($query) use ($filters) {
                $query->where('chief_id', $filters['chief_id']);
            })
            ->get();

        $filename = 'allocations-report-' . date('Y-m-d') . '.csv';
        $headers = [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => "attachment; filename=\"$filename\"",
        ];

        $callback = function() use ($allocations) {
            $file = fopen('php://output', 'w');
            fwrite($file, "\xEF\xBB\xBF"); // UTF-8 BOM
            
            fputcsv($file, [
                'ID', 'Land', 'Client', 'Chief', 'Allocation Date', 
                'Approval Status', 'Payment Status'
            ]);
            
            foreach ($allocations as $allocation) {
                fputcsv($file, [
                    $allocation->id,
                    $allocation->land->plot_number ?? 'N/A',
                    $allocation->client->full_name ?? 'N/A',
                    $allocation->chief->name ?? 'No Chief',
                    $allocation->allocation_date?->format('Y-m-d') ?? '',
                    $allocation->approval_status ?? 'pending',
                    $allocation->payment_status ?? 'unpaid',
                ]);
            }
            
            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }

    /**
     * Display clients report (HTML view)
     */
    public function clientReport(Request $request): View
    {
        $request->validate([
            'start_date' => 'nullable|date',
            'end_date' => 'nullable|date|after_or_equal:start_date',
            'status' => 'nullable|string'
        ]);

        $clients = Client::with(['allocations.land'])
            ->when($request->start_date, function($query) use ($request) {
                $query->where('created_at', '>=', $request->start_date);
            })
            ->when($request->end_date, function($query) use ($request) {
                $query->where('created_at', '<=', $request->end_date);
            })
            ->when($request->status, function($query) use ($request) {
                $query->where('is_active', $request->status === 'active');
            })
            ->latest()
            ->get();

        return view('reports.clients', compact('clients'));
    }

    /**
     * Generate and download client report (PDF/Excel)
     */
    public function generateClientReport(Request $request)
    {
        $request->validate([
            'start_date' => 'nullable|date',
            'end_date' => 'nullable|date|after_or_equal:start_date',
            'status' => 'nullable|string',
            'format' => 'required|in:pdf,excel'
        ]);

        // For now, redirect to CSV export to avoid Excel package issues
        if ($request->format === 'excel') {
            return $this->exportClientReport($request);
        }

        // PDF report
        $clients = Client::with(['allocations.land'])
            ->when($request->start_date, function($query) use ($request) {
                $query->where('created_at', '>=', $request->start_date);
            })
            ->when($request->end_date, function($query) use ($request) {
                $query->where('created_at', '<=', $request->end_date);
            })
            ->when($request->status, function($query) use ($request) {
                $query->where('is_active', $request->status === 'active');
            })
            ->get();

        $pdf = PDF::loadView('reports.clients-pdf', compact('clients'));

        // Save report record
        Report::create([
            'name' => 'Clients Report - ' . date('Y-m-d'),
            'type' => 'clients',
            'date_range' => [
                'start' => $request->start_date,
                'end' => $request->end_date
            ],
            'generated_by' => auth()->id(),
            'file_path' => 'reports/clients-report-' . date('Y-m-d') . '.pdf',
            'parameters' => $request->all()
        ]);

        return $pdf->download('clients-report-' . date('Y-m-d') . '.pdf');
    }

    /**
     * Quick export client report
     */
    public function exportClientReport(Request $request)
    {
        $filters = $request->only(['start_date', 'end_date', 'status']);
        
        // Create CSV export for clients
        $clients = Client::with(['allocations.land'])
            ->when($filters['start_date'] ?? null, function($query) use ($filters) {
                $query->where('created_at', '>=', $filters['start_date']);
            })
            ->when($filters['end_date'] ?? null, function($query) use ($filters) {
                $query->where('created_at', '<=', $filters['end_date']);
            })
            ->when($filters['status'] ?? null, function($query) use ($filters) {
                $query->where('is_active', $filters['status'] === 'active');
            })
            ->get();

        $filename = 'clients-report-' . date('Y-m-d') . '.csv';
        $headers = [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => "attachment; filename=\"$filename\"",
        ];

        $callback = function() use ($clients) {
            $file = fopen('php://output', 'w');
            fwrite($file, "\xEF\xBB\xBF"); // UTF-8 BOM
            
            fputcsv($file, [
                'ID', 'Full Name', 'Phone', 'Email', 'ID Number', 
                'Status', 'Allocations Count', 'Created At'
            ]);
            
            foreach ($clients as $client) {
                fputcsv($file, [
                    $client->id,
                    $client->full_name ?? 'N/A',
                    $client->phone ?? 'N/A',
                    $client->email ?? 'N/A',
                    $client->id_number ?? 'N/A',
                    $client->is_active ? 'Active' : 'Inactive',
                    $client->allocations->count(),
                    $client->created_at?->format('Y-m-d') ?? '',
                ]);
            }
            
            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }

    /**
     * Display chiefs report (HTML view)
     */
    public function chiefReport(Request $request): View
    {
        $request->validate([
            'start_date' => 'nullable|date',
            'end_date' => 'nullable|date|after_or_equal:start_date',
            'region' => 'nullable|string'
        ]);

        $chiefs = Chief::with(['lands', 'lands.allocation'])
            ->when($request->start_date, function($query) use ($request) {
                $query->where('created_at', '>=', $request->start_date);
            })
            ->when($request->end_date, function($query) use ($request) {
                $query->where('created_at', '<=', $request->end_date);
            })
            ->when($request->region, function($query) use ($request) {
                $query->where('region', $request->region);
            })
            ->latest()
            ->get();

        return view('reports.chiefs', compact('chiefs'));
    }

    /**
     * Generate and download chief report (PDF/Excel)
     */
    public function generateChiefReport(Request $request)
    {
        $request->validate([
            'start_date' => 'nullable|date',
            'end_date' => 'nullable|date|after_or_equal:start_date',
            'region' => 'nullable|string',
            'format' => 'required|in:pdf,excel'
        ]);

        // For now, redirect to CSV export to avoid Excel package issues
        if ($request->format === 'excel') {
            return $this->exportChiefReport($request);
        }

        // PDF report
        $chiefs = Chief::with(['lands', 'lands.allocation'])
            ->when($request->start_date, function($query) use ($request) {
                $query->where('created_at', '>=', $request->start_date);
            })
            ->when($request->end_date, function($query) use ($request) {
                $query->where('created_at', '<=', $request->end_date);
            })
            ->when($request->region, function($query) use ($request) {
                $query->where('region', $request->region);
            })
            ->get();

        $pdf = PDF::loadView('reports.chiefs-pdf', compact('chiefs'));

        // Save report record
        Report::create([
            'name' => 'Chiefs Report - ' . date('Y-m-d'),
            'type' => 'chiefs',
            'date_range' => [
                'start' => $request->start_date,
                'end' => $request->end_date
            ],
            'generated_by' => auth()->id(),
            'file_path' => 'reports/chiefs-report-' . date('Y-m-d') . '.pdf',
            'parameters' => $request->all()
        ]);

        return $pdf->download('chiefs-report-' . date('Y-m-d') . '.pdf');
    }

    /**
     * Quick export chief report
     */
    public function exportChiefReport(Request $request)
    {
        $filters = $request->only(['start_date', 'end_date', 'region']);
        
        // Create CSV export for chiefs
        $chiefs = Chief::with(['lands', 'lands.allocation'])
            ->when($filters['start_date'] ?? null, function($query) use ($filters) {
                $query->where('created_at', '>=', $filters['start_date']);
            })
            ->when($filters['end_date'] ?? null, function($query) use ($filters) {
                $query->where('created_at', '<=', $filters['end_date']);
            })
            ->when($filters['region'] ?? null, function($query) use ($filters) {
                $query->where('region', $filters['region']);
            })
            ->get();

        $filename = 'chiefs-report-' . date('Y-m-d') . '.csv';
        $headers = [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => "attachment; filename=\"$filename\"",
        ];

        $callback = function() use ($chiefs) {
            $file = fopen('php://output', 'w');
            fwrite($file, "\xEF\xBB\xBF"); // UTF-8 BOM
            
            fputcsv($file, [
                'ID', 'Name', 'Region', 'Community', 'Phone', 
                'Lands Count', 'Status', 'Created At'
            ]);
            
            foreach ($chiefs as $chief) {
                fputcsv($file, [
                    $chief->id,
                    $chief->name ?? 'N/A',
                    $chief->region ?? 'N/A',
                    $chief->community ?? 'N/A',
                    $chief->phone ?? 'N/A',
                    $chief->lands->count(),
                    $chief->is_active ? 'Active' : 'Inactive',
                    $chief->created_at?->format('Y-m-d') ?? '',
                ]);
            }
            
            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }

    /**
     * Display system report (HTML view)
     */
    public function systemReport(Request $request): View
    {
        $stats = [
            'total_users' => User::count(),
            'active_users' => User::where('is_active', true)->count(),
            'total_lands' => Land::count(),
            'total_clients' => Client::count(),
            'total_chiefs' => Chief::count(),
            'total_allocations' => Allocation::count(),
            'pending_allocations' => Allocation::where('approval_status', 'pending')->count(),
            'storage_usage' => $this->getStorageUsage(),
        ];

        return view('reports.system', compact('stats'));
    }

    /**
     * Generate and download system report (PDF/Excel)
     */
    public function generateSystemReport(Request $request)
    {
        $request->validate([
            'format' => 'required|in:pdf,excel'
        ]);

        // For now, redirect to CSV export to avoid Excel package issues
        if ($request->format === 'excel') {
            return $this->exportSystemReport();
        }

        // PDF report
        $stats = [
            'total_users' => User::count(),
            'active_users' => User::where('is_active', true)->count(),
            'total_lands' => Land::count(),
            'total_clients' => Client::count(),
            'total_chiefs' => Chief::count(),
            'total_allocations' => Allocation::count(),
            'pending_allocations' => Allocation::where('approval_status', 'pending')->count(),
            'storage_usage' => $this->getStorageUsage(),
        ];

        $pdf = PDF::loadView('reports.system-pdf', compact('stats'));

        // Save report record
        Report::create([
            'name' => 'System Report - ' . date('Y-m-d'),
            'type' => 'system',
            'generated_by' => auth()->id(),
            'file_path' => 'reports/system-report-' . date('Y-m-d') . '.pdf',
            'parameters' => $request->all()
        ]);

        return $pdf->download('system-report-' . date('Y-m-d') . '.pdf');
    }

    /**
     * Quick export system report
     */
    public function exportSystemReport()
    {
        $stats = [
            'total_users' => User::count(),
            'active_users' => User::where('is_active', true)->count(),
            'total_lands' => Land::count(),
            'total_clients' => Client::count(),
            'total_chiefs' => Chief::count(),
            'total_allocations' => Allocation::count(),
            'pending_allocations' => Allocation::where('approval_status', 'pending')->count(),
        ];

        $filename = 'system-report-' . date('Y-m-d') . '.csv';
        $headers = [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => "attachment; filename=\"$filename\"",
        ];

        $callback = function() use ($stats) {
            $file = fopen('php://output', 'w');
            fwrite($file, "\xEF\xBB\xBF"); // UTF-8 BOM
            
            fputcsv($file, ['Metric', 'Value']);
            
            foreach ($stats as $key => $value) {
                $metricName = str_replace('_', ' ', ucwords($key));
                fputcsv($file, [$metricName, $value]);
            }
            
            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }

    /**
     * Download generated report
     */
    public function download(Report $report)
    {
        if (!file_exists(storage_path('app/' . $report->file_path))) {
            return redirect()->back()->with('error', 'Report file not found.');
        }

        return response()->download(storage_path('app/' . $report->file_path));
    }

    public function destroy(Report $report): RedirectResponse
    {
        $report->delete();
        return redirect()->route('reports.index')->with('success', 'Report deleted successfully!');
    }

    /**
     * Calculate storage usage
     */
    private function getStorageUsage(): array
    {
        $totalSize = 0;
        $path = storage_path('app');
        
        try {
            foreach (new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($path)) as $file) {
                if ($file->isFile()) {
                    $totalSize += $file->getSize();
                }
            }
        } catch (\Exception $e) {
            $totalSize = 0;
        }

        return [
            'total' => $totalSize,
            'formatted' => $this->formatBytes($totalSize)
        ];
    }

    /**
     * Format bytes to human readable format
     */
    private function formatBytes($bytes, $precision = 2): string
    {
        $units = ['B', 'KB', 'MB', 'GB', 'TB'];
        $bytes = max($bytes, 0);
        $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
        $pow = min($pow, count($units) - 1);
        $bytes /= pow(1024, $pow);

        return round($bytes, $precision) . ' ' . $units[$pow];
    }
}